PREFIX cti:  <http://gic.ufrpe.br/cti/vocabulary/cti#>

SELECT ?ppg ?codigo ?nome ?conceito ?ano
WHERE {
	?ppg a cti:PPG ;
		cti:cd_programa_ies ?codigo ;
		cti:nm_programa_ies ?nome ;
		cti:avaliado ?conceitoInd .

	?conceitoInd cti:cd_conceito_programa ?conceito ;
				 cti:an_base_conceito ?ano .
}
ORDER BY ?codigo